console.log("----------------------------------------");
console.log("Lesson13:Boc tach mang (Array)");
console.log("Boc tach 1 Array ra thanh cac bien");
console.log("Ap dung duoc dang Rest Paramter");
let employees = ["A", "B"];
let [emp1, emp2, emp3] = employees;
// let [emp1, ...emp2] = employees;
console.log(emp1);
console.log(emp2);
console.log(emp3);